### PR TITLE
Add namespaces / global usings

### PR DESCRIPTION
**Pull request by valkyrienyanko**
This PR surrounds all classes with the namespace FlappyBird and adds global using Godot; to game manager class.

### CODE REVIEW

**Comment by lorenzo774** [comment]
Thank you for your contribution!

**Comment by lorenzo774** [comment]
@valkyrienyanko I had a lot of trouble building the game with Godot Mono.

**Comment by valkyrienyanko** [comment]
For me I find GDScript super confusing and C# to be very straight forward

**Comment by lorenzo774** [comment]
Yes it's very straight forward with C#, but it was hard to get it working.

**Comment by valkyrienyanko** [comment]
Yeah I can imagine, I can't seem to finish a single game myself 😂 lol

**Comment by lorenzo774** [comment]
I can't open the project right now, maybe because of ```AppData```  problem or .NET version, I really don't know 😂😂

**Comment by valkyrienyanko** [comment]
Make sure you have [.NET SDK](https://dotnet.microsoft.com/en-us/download) and [.NET Framework 4.7.2](https://duckduckgo.com/?q=.net+framework+4.7.2)

**Comment by lorenzo774** [comment]
I have both of them.

**Comment by valkyrienyanko** [comment]
FYI I opened your project with Godot mono 3.4.4

**Comment by lorenzo774** [comment]
Oh, I have tried with ```3.2.3```, I will now download the new version.

**Comment by valkyrienyanko** [comment]
I believe the latest version right now is 3.4.5

**Comment by lorenzo774** [comment]
Yes

**Comment by lorenzo774** [comment]
It's working.

**Pull request merged**
